/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TecladoNumericoPanel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author carlos
 */
public class TecladoNumericoPanel extends javax.swing.JPanel {
    // VARIABLE PARA SABER DÓNDE ESCRIBIR
    private JTextComponent campoDestino;

    // MÉTODO PARA RECIBIR LA CAJA DE TEXTO DESDE OTRA VENTANA
    public void setCampoDestino(JTextComponent campo) {
        this.campoDestino = campo;
    }

    // MÉTODO AUXILIAR PARA NO REPETIR CÓDIGO EN CADA BOTÓN
    private void agregarNumero(String numero) {
        if (campoDestino != null) {
            String textoActual = campoDestino.getText();
            campoDestino.setText(textoActual + numero);
            
            // Si usas JToggleButton, esto hace que el botón se "levante" visualmente después del clic
            // Si no te importa que se quede hundido, puedes borrar las siguientes líneas
            if(campoDestino.hasFocus()) {
                campoDestino.requestFocus(); 
            }
        }
    }

    /**
     * Creates new form TecladoNumericoPanel
     */
    public TecladoNumericoPanel() {
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn1.addActionListener(this::btn1ActionPerformed);
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        btn2.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.addActionListener(this::btn2ActionPerformed);
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        btn3.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.addActionListener(this::btn3ActionPerformed);
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        btn4.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.addActionListener(this::btn4ActionPerformed);
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        btn5.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.addActionListener(this::btn5ActionPerformed);
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        btn6.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.addActionListener(this::btn6ActionPerformed);
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, -1));

        btn7.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.addActionListener(this::btn7ActionPerformed);
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        btn8.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setContentAreaFilled(false);
        btn8.setDefaultCapable(false);
        btn8.addActionListener(this::btn8ActionPerformed);
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));

        btn9.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setContentAreaFilled(false);
        btn9.setDefaultCapable(false);
        btn9.addActionListener(this::btn9ActionPerformed);
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        btn0.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.setContentAreaFilled(false);
        btn0.setDefaultCapable(false);
        btn0.addActionListener(this::btn0ActionPerformed);
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        btnBorrar.setFont(new java.awt.Font("Roboto Black", 0, 60)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.setBorder(null);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setDefaultCapable(false);
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 270, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        agregarNumero("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        agregarNumero("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        agregarNumero("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        agregarNumero("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        agregarNumero("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        agregarNumero("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        agregarNumero("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        agregarNumero("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        agregarNumero("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        agregarNumero("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if (campoDestino != null) {
            String texto = campoDestino.getText();
            if (texto.length() > 0) {
                campoDestino.setText(texto.substring(0, texto.length() - 1));
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
