/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.loguinp2;
import TecladoNumericoPanel.TecladoNumericoPanel; 
import java.awt.BorderLayout; 
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author carlos
 */
public class loguinp2 extends javax.swing.JFrame {
private TecladoNumericoPanel teclado;
    
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loguinp2.class.getName());

    /**
     * Creates new form loguinp2
     */
    public loguinp2() {
        initComponents();
        this.setLocationRelativeTo(null);
        teclado = new TecladoNumericoPanel();
        connet.setLayout(new BorderLayout());
        connet.add(teclado, BorderLayout.CENTER);

   
    

  
    connet.revalidate();
    connet.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Passtxt = new javax.swing.JPasswordField();
        userTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        connet = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Condensed Light", 0, 36)); // NOI18N
        jLabel3.setText("CONTRASEÑA");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, -1));

        title.setFont(new java.awt.Font("Roboto Condensed Light", 0, 36)); // NOI18N
        title.setText("USUARIO");
        jPanel3.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/gg-removebg-preview.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 410, 350));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setAlignmentX(0.7F);
        jSeparator1.setAlignmentY(0.7F);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, 490, 30));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setAlignmentX(0.7F);
        jSeparator2.setAlignmentY(0.7F);
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 490, 30));

        Passtxt.setBackground(new java.awt.Color(97, 164, 191));
        Passtxt.setFont(new java.awt.Font("Roboto SemiCondensed Medium", 3, 60)); // NOI18N
        Passtxt.setForeground(new java.awt.Color(204, 204, 204));
        Passtxt.setText("contaseña");
        Passtxt.setToolTipText("");
        Passtxt.setBorder(null);
        Passtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasstxtMousePressed(evt);
            }
        });
        Passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasstxtActionPerformed(evt);
            }
        });
        jPanel3.add(Passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 490, 50));
        Passtxt.getAccessibleContext().setAccessibleName("");

        userTxt.setBackground(new java.awt.Color(97, 164, 191));
        userTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userTxt.setForeground(new java.awt.Color(204, 204, 204));
        userTxt.setText("INGRESE SU DNI");
        userTxt.setBorder(null);
        userTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel3.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 490, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/city-building-background-vector.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 620, 800));

        connet.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout connetLayout = new javax.swing.GroupLayout(connet);
        connet.setLayout(connetLayout);
        connetLayout.setHorizontalGroup(
            connetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        connetLayout.setVerticalGroup(
            connetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(connet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 800));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 700, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasstxtActionPerformed

    private void PasstxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasstxtMousePressed
        // TODO add your handling code here:
      teclado.setCampoDestino(Passtxt);
        
       
        if (String.valueOf(Passtxt.getPassword()).equals("contaseña")) { 
            Passtxt.setText("");
            Passtxt.setForeground(java.awt.Color.BLACK);
        }
        
        
        if (userTxt.getText().isEmpty()) {
            userTxt.setText("INGRESE SU DNI");
            userTxt.setForeground(new java.awt.Color(204, 204, 204));
        }
        
    }//GEN-LAST:event_PasstxtMousePressed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
   teclado.setCampoDestino(userTxt);
        
        // 2. Lógica para manejar el placeholder
        if (userTxt.getText().equals("INGRESE SU DNI")) {
            userTxt.setText(""); 
            userTxt.setForeground(java.awt.Color.BLACK); 
        }
        
    
        if (String.valueOf(Passtxt.getPassword()).isEmpty()) {
            Passtxt.setText("contaseña");
            Passtxt.setForeground(new java.awt.Color(204, 204, 204));
        }

    
    }//GEN-LAST:event_userTxtMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loguinp2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passtxt;
    private javax.swing.JPanel connet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
